Fix Java and Bazel version when building with Bazel in GitHub Actions.
This CL fixes the version of Java to JDK8 and Bazel to 3.7.1

For Java, ubuntu-latest will soon be switching from Java 8 to Java 11 as the default (https://github.com/actions/virtual-environments/issues/1816), and our Bazel builds currently don't work with Java 11 since compile_testing depends on @local_jdk//:lib/tools.jar which doesn't exist in Java 11.

https://github.com/google/bazel-common/blob/master/third_party/java/compile_testing/BUILD#L32

For Bazel, ubuntu-latest currently uses Bazel 4.0.0 by default, which fails with Robolectric tests @Config annotation:

```
error: missing required annotation argument: <clinit> @Config
```
RELNOTES=N/A
PiperOrigin-RevId: 358062883